enum IFacetType {
  SELECTION = "SELECTION",
  MULTISELECTION = "MULTISELECTION",
  DATEPICKER = "DATEPICKER",
  TEXTAREA = "FACETTEXTAREA",
  BOOLEAN = "FACETBOOLEAN",
  USERSELECTION = "USERSELECTION",
  PERCENTAGE = "PERCENTAGE",
  DICTIONARY = "DICTIONARY",
  CATEGORY = "CATEGORY",
}

export default IFacetType;
