import { TypeCell } from "../../componentsBase/StickyGrid";
import { IColumnSc } from "../../interfaces";

const columns: IColumnSc[] = [
  {
    id: "level",
    label: "level",
    type: TypeCell.String,
    sortable: false,
    groupId: "default",
    width: 110,
    scope: [],
  },
  {
    id: "attributeType",
    label: "attributeType",
    type: TypeCell.String,
    sortable: false,
    groupId: "default",
    width: 110,
    scope: [],
  },
  {
    id: "attributeFamily",
    label: "attributeFamily",
    type: TypeCell.String,
    sortable: false,
    groupId: "default",
    width: 110,
    scope: [],
  },
  {
    id: "atype",
    label: "atype",
    type: TypeCell.String,
    sortable: false,
    groupId: "default",
    width: 110,
    scope: [],
  },
  {
    id: "attributeName",
    label: "attributeName",
    type: TypeCell.String,
    sortable: false,
    groupId: "default",
    width: 180,
    scope: [],
  },
  {
    id: "label",
    label: "label",
    type: TypeCell.String,
    sortable: false,
    groupId: "default",
    width: 180,
    scope: [],
  },
  {
    id: "mandatory",
    label: "mandatory",
    type: TypeCell.Bool,
    sortable: false,
    groupId: "default",
    width: 90,
    scope: [],
  },
  {
    id: "groupId",
    label: "groupId",
    type: TypeCell.String,
    sortable: false,
    groupId: "default",
    width: 90,
    scope: [],
  },
  {
    id: "exportable",
    label: "exportable",
    type: TypeCell.Bool,
    sortable: false,
    groupId: "default",
    width: 90,
    scope: [],
  },
  {
    id: "editable",
    label: "editable",
    type: TypeCell.Bool,
    sortable: false,
    groupId: "default",
    width: 90,
    scope: [],
  },
  {
    id: "searchable",
    label: "searchable",
    type: TypeCell.Bool,
    sortable: false,
    groupId: "default",
    width: 90,
    scope: [],
  },
  {
    id: "carryOver",
    label: "carryOver",
    type: TypeCell.Bool,
    sortable: false,
    groupId: "default",
    width: 90,
    scope: [],
  },
  {
    id: "multiCatalog",
    label: "multiCatalog",
    type: TypeCell.Bool,
    sortable: false,
    groupId: "default",
    width: 90,
    scope: [],
  },
  {
    id: "multiLanguage",
    label: "multiLanguage",
    type: TypeCell.Bool,
    sortable: false,
    groupId: "default",
    width: 90,
    scope: [],
  },
  {
    id: "dictionary",
    label: "dictionary",
    type: TypeCell.String,
    sortable: false,
    groupId: "default",
    width: 180,
    scope: [],
  },
];

export default columns;
